import json
from openai import OpenAI


text = '''frame four questions for the following text:
Moreover, attachment to things other than the Self leads to bondage. With this awareness, we get rid of the thirst for various desires. With this and a little effort from the intellect, the mind can be brought under our grip.
The pursuit of the Self is indeed impossible - even with very heavy effort - if the mind is not under control. A person needs to bring his mind under control, persevering by working independent of desire to worship Me.
With this, he gains the ability to practice yoga . He gains the ability to see everything with equanimity.'''

# the first four questions are generated by questioner.py
questions = ['What does attachment lead to?',
             'How can desire be controlled?',
             'Why is controlling the mind important?',
             'What ability is gained through yoga?',
             'What is discipline in the quality of rajas?', # this question is manually entered, slightly out of context
             'Why is Arjuna ambivalent?']                   # this one is also manual, totally out of context


def question_to_embedding(question):
    print(f'creating embedding for: {question}')
    return client.embeddings.create(input = [question], model='text-embedding-3-small').data[0].embedding


client = OpenAI()

text = text.replace("\n", " ")
print('creating text embedding...')
text_embedding = client.embeddings.create(input = [text], model="text-embedding-3-small").data[0].embedding
print('mapping question embeddings...')
question_embeddings = list(map(question_to_embedding, questions))
with open('embeddings.json', 'w') as f:
    json.dump({
        "text_embedding": text_embedding,
        "question_embeddings": question_embeddings
    }, f)
print('wrote embeddings to embeddings.json')
