import json
import tensorflow_hub as hub 


text = '''frame four questions for the following text:
Moreover, attachment to things other than the Self leads to bondage. With this awareness, we get rid of the thirst for various desires. With this and a little effort from the intellect, the mind can be brought under our grip.
The pursuit of the Self is indeed impossible - even with very heavy effort - if the mind is not under control. A person needs to bring his mind under control, persevering by working independent of desire to worship Me.
With this, he gains the ability to practice yoga . He gains the ability to see everything with equanimity.'''

# the first four questions are generated by questioner.py
questions = ['What does attachment lead to?',
             'How can desire be controlled?',
             'Why is controlling the mind important?',
             'What ability is gained through yoga?',
             'What is discipline in the quality of rajas?', # this question is manually entered, slightly out of context
             'Why is Arjuna ambivalent?']                   # this one is also manual, totally out of context


embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4") 

text = text.replace("\n", " ")
print('creating text embedding...')
text_embedding = embed([text])
print('creating question embeddings...')
question_embeddings = embed(questions)

with open('univsent-embeddings.json', 'w') as f:
    json.dump({
        "text_embedding": text_embedding.numpy().tolist()[0],
        "question_embeddings": question_embeddings.numpy().tolist()
    }, f)
print('wrote embeddings to univsent-embeddings.json')
